version: '3.8'

services:
  go-test-lamoda:
    build: ./
    command: ./wait-for-postgres.sh db ./go-test-lamoda
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/stockdb?sslmode=disable

  db:
    restart: always
    image: postgres:latest
    networks:
      new:
        aliases:
          - db
    volumes:
      - /path/to/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stockdb
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - .:/migrations
    command: ["-path", "./migrations", "-database",  "postgres://user:password@db:5432/stockdb?sslmode=disable", "up", "3"]
    depends_on:
      - db

networks:
  new: